baseURL = "https://dustymabe.com"
languageCode = "en-us"
title = "A Random Walk Down Tech Street"
theme = "beautifulhugo"

[Params]
  subtitle = "musings of a computer engineer"
  logo = "img/dustymabecom-logo.png"
  favicon = "img/dustymabecom-favicon.ico"
  dateFormat = "January 2, 2006"
  commit = "https://github.com/dustymabe/dustymabe.com/tree/"
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Dusty Mabe"
  email = "dusty@dustymabe.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "dustymabe"
  gitlab = "dustymabe"
  twitter = "dustymabe"
  #reddit = "username"
  linkedin = "dustymabe"
  #xing = "username"
  stackoverflow = "users/2869277/dustymabe"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

#[[menu.main]]
#    name = "About"
#    url = "page/about/"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[permalinks]
    post = "/:year/:month/:day/:title/"

# Allow for raw html to be processed
# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
# https://gohugo.io/news/0.60.0-relnotes/
[markup.goldmark.renderer]
unsafe= true
